### PR TITLE
General improvements.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Here's a set of general improvements made to Plumtree to in building support for Plumtree into the Lasp programming language.  These changes resolve a series of Dialyzer warnings, address race conditions in creation of local state, and local mutations of membership state.

I tested these changes under Erlang 16 (with additional patches not included in this PR), but was unable to get the common test suite to run, so I was unable to verify that.

Comments welcome.

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Any thoughts here?

**Comment by cmeiklejohn** [comment]
So, any thoughts here?

**Comment by tsantero** [comment]
@cmeiklejohn sorry for the delay. this patch looks good, and will be merged this week..just going to fix up the type errors for Travis before pulling the trigger

**Comment by cmeiklejohn** [comment]
OK; keep me informed.  I'd like to have it so we can delete our fork.

**Comment by tsantero** [comment]
@cmeiklejohn i see the branch on Lasp has made forward progress since this PR was opened. Do you want to push latest commits? will merge.

**Comment by sargun** [comment]
@tsantero Any plans to merge this PR?

**Comment by tsantero** [comment]
closing, as https://github.com/helium/plumtree/pull/26 applied these commits, which are now on master.

**Pull request closed without merging**
